// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function map2(a, b, f) {
  if (a !== undefined && b !== undefined) {
    return Caml_option.some(f(Caml_option.valFromOption(a), Caml_option.valFromOption(b)));
  }
  
}

export {
  map2 ,
}
/* No side effect */
